import type { Edge, Node } from '@xyflow/react';
import type { ExecutionResult, FlowGraph, FlowNodeData } from '../types';
const stages = ['request', 'rate_limit', 'security', 'routing', 'token_budget', 'cache_lookup', 'provider_call', 'retry', 'fallback', 'validation', 'correction', 'completion'];
const labels: Record<string, string> = { request: 'Request', rate_limit: 'Rate Limit', security: 'Prompt Security', routing: 'Model Router', token_budget: 'Token Budget', cache_lookup: 'Response Cache', provider_call: 'LLM Provider', retry: 'Retry Controller', fallback: 'Fallback', validation: 'Structured Validation', correction: 'Correction', completion: 'Response' };
export function mapExecution(result?: ExecutionResult, replayIndex = Number.POSITIVE_INFINITY): FlowGraph {
  const spans = result?.trace ?? []; const completed = new Map(spans.slice(0, replayIndex + 1).map((span) => [span.name, span]));
  const providerFailed = spans.some((span) => span.name === 'provider_call' && span.status === 'failed');
  const nodes: Node<FlowNodeData>[] = stages.map((stage, index) => { const span = completed.get(stage); let status = span?.status ?? (result && result.security.allowed === false && index > 2 ? 'skipped' : 'idle'); if (stage === 'provider_call' && result?.fallback_used && providerFailed) status = 'warning'; if (stage === 'retry' && result && result.retry_count > 0) status = 'succeeded'; if (stage === 'fallback' && result?.fallback_used) status = 'succeeded'; if (stage === 'provider_call' && result?.cache_hit) status = 'skipped'; const info = stage === 'routing' ? result?.routing_reason : stage === 'provider_call' ? (result?.fallback_used ? `${result.attempted_providers.join(' → ')} → ${result.provider}` : result?.provider) : stage === 'retry' && result?.retry_count ? `${result.retry_count} retry` : stage === 'cache_lookup' ? (result?.cache_hit ? 'HIT' : 'MISS') : undefined; return { id: stage, type: 'stage', position: { x: (index % 4) * 230, y: Math.floor(index / 4) * 150 }, data: { label: labels[stage], status, info } }; });
  const edges: Edge[] = stages.slice(0, -1).map((stage, index) => ({ id: `e-${stage}`, source: stage, target: stages[index + 1], label: completed.get(stages[index + 1])?.status === 'cache_hit' ? 'hit' : undefined, animated: Boolean(completed.get(stages[index + 1])) })); return { nodes, edges };
}
